import { useI18n } from '../i18n';
import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { PanelRight, Eye, FileText, ListTree, Maximize2 } from 'lucide-react';
import { baseRun, createStyle, resolveStyle, resolveTableStyle, paragraphStyle, type Run, type Paragraph, type Project, type Style, type List, type Level, type Border } from '../model';
import { levelLabel, simulateList, listTestSequence, parseListTestSequence } from '../numbering';
import { defaultTableLook, resolveTableCell, tablePreviewSize, type TableLook } from '../tablePreview';

const cm=37.7953;
const highlights:Record<string,string>={darkBlue:'#000080',darkCyan:'#008080',darkGreen:'#008000',darkMagenta:'#800080',darkRed:'#800000',darkYellow:'#808000',darkGray:'#808080',lightGray:'#c0c0c0'};
export function runCss(run:Run):CSSProperties{
 const r={...baseRun,...run};const fallback:Record<string,string>={'宋体':'"Songti SC", SimSun','楷体':'"Kaiti SC", KaiTi','黑体':'"Heiti SC", SimHei'};
 return {fontFamily:`"${r.latinFont.replaceAll('"','')}", "${r.font.replaceAll('"','')}", ${fallback[r.font]??''}${fallback[r.font]?', ':''}serif`,fontSize:`${r.size}pt`,fontWeight:r.bold?700:400,fontStyle:r.italic?'italic':'normal',color:r.color,textDecorationLine:[r.underline!=='none'?'underline':'',r.strike!=='none'?'line-through':''].join(' ').trim()||'none',textDecorationStyle:r.underline==='double'||r.strike==='double'?'double':r.underline==='dotted'?'dotted':r.underline==='dash'?'dashed':r.underline==='wave'?'wavy':'solid',textDecorationColor:r.underlineColor,letterSpacing:`${r.spacing}pt`,fontVariantCaps:r.smallCaps?'small-caps':'normal',textTransform:r.caps?'uppercase':'none',verticalAlign:r.script==='superscript'?'super':r.script==='subscript'?'sub':'baseline',position:r.position?'relative':undefined,top:r.position?`${-r.position}pt`:undefined,textShadow:r.shadow?'1px 1px 2px #aaa':undefined,WebkitTextStroke:r.outline?`0.5px ${r.color}`:undefined,opacity:r.hidden?0.32:1,backgroundColor:r.highlight!=='none'?(highlights[r.highlight]??r.highlight):r.shading==='#ffffff'?undefined:r.shading,fontVariantNumeric:[r.numForm==='oldStyle'?'oldstyle-nums':r.numForm==='lining'?'lining-nums':'',r.numSpacing==='tabular'?'tabular-nums':r.numSpacing==='proportional'?'proportional-nums':''].filter(Boolean).join(' ')||'normal'};
}
export function paragraphCss(p:Paragraph,run:Run):CSSProperties{
 const c:CSSProperties={textAlign:p.alignment==='both'||p.alignment==='distribute'?'justify':p.alignment,textAlignLast:p.alignment==='distribute'?'justify':undefined,lineHeight:p.lineRule==='auto'?p.line:`${p.line}pt`,marginTop:p.spacingUnit==='line'?`${p.before??0}em`:`${p.before??0}pt`,marginBottom:p.spacingUnit==='line'?`${p.after??0}em`:`${p.after??0}pt`,paddingLeft:p.indentUnit==='char'?`${p.left??0}em`:(p.left??0)*cm,paddingRight:p.indentUnit==='char'?`${p.right??0}em`:(p.right??0)*cm,textIndent:p.indentUnit==='char'?`${p.firstLine??0}em`:(p.firstLine??0)*cm,backgroundColor:p.shading,direction:p.bidi?'rtl':'ltr',minHeight:`${(run.size??12)*1.2}pt`};
 for(const side of ['top','bottom','left','right'] as const){const b=p.borders?.[side];if(b&&b.style!=='none'){const property=`border${side[0].toUpperCase()+side.slice(1)}` as keyof CSSProperties;Object.assign(c,{[property]:`${b.width}pt ${b.style==='double'?'double':b.style==='dotted'?'dotted':b.style==='dashed'?'dashed':'solid'} ${b.color}`});}}
 return c;
}
function borderCss(border:Border):string {
 return border.style==='none'?'none':`${border.width}pt ${border.style==='double'?'double':border.style==='dotted'?'dotted':border.style==='dashed'?'dashed':'solid'} ${border.color}`;
}
export function TablePreview({style,project,report=false,onSelect,look=defaultTableLook}:{style:Style;project:Project;report?:boolean;onSelect?:(id:string)=>void;look?:TableLook}){
 const {ui,fmt,diagnostic,t}=useI18n();
 const table=resolveTableStyle(project,style);if(!table)return null;
 const {rows,cols}=tablePreviewSize(table,look);
 const shortRows=[[ui("项目"),ui("样式设置"),ui("效果")],[ui("标题"),ui("层级与编号"),ui("清晰有序")],[ui("正文"),ui("字体与行距"),ui("阅读舒适")],[ui("表格"),ui("边框与底纹"),ui("保持统一")]];
 return <table className="sample-table" aria-label={fmt("{0}预览",style.name)} style={{borderCollapse:table.cellSpacing?'separate':'collapse',borderSpacing:table.cellSpacing*cm,tableLayout:'fixed'}}><tbody>{Array.from({length:rows},(_,i)=><tr key={i}>{Array.from({length:cols},(_,j)=>{
   const contentStyle=report?project.styles.find(s=>s.id===(i===0?'TableHeader':i===rows-1?'TableFooter':j===0?'TableBodyLeft':j===cols-1?'TableBodyRight':'TableBodyCenter')):undefined;
   const cell=rows===4&&cols===3?shortRows[i][j]:i===0?(j===0?ui("项目"):fmt("第 {0} 列",j+1)):i===rows-1?ui("合计"):j===0?fmt("条目 {0}",i):fmt("内容 {0}.{1}",i,j+1);
   const resolved=resolveTableCell(project,style,table,i,j,rows,cols,look,contentStyle);
   const {run,paragraph,borders,shading,verticalAlign,paragraphShading}=resolved;
   return <td key={j} style={{padding:(['top','right','bottom','left'] as const).map(side=>`${(table.cellMargins?.[side]??table.cellMargin)*cm}px`).join(' '),background:shading,verticalAlign:verticalAlign==='center'?'middle':verticalAlign,borderTop:borderCss(borders.top),borderBottom:borderCss(borders.bottom),borderLeft:borderCss(borders.left),borderRight:borderCss(borders.right)}}><p title={contentStyle?fmt("编辑 {0}",contentStyle.name):undefined} role={contentStyle?'button':undefined} tabIndex={contentStyle?0:undefined} onClick={()=>contentStyle&&onSelect?.(contentStyle.id)} onKeyDown={e=>{if(contentStyle&&e.key==='Enter')onSelect?.(contentStyle.id);}} style={{...runCss(run),...paragraphCss(paragraph,run),backgroundColor:paragraphShading}}>{cell}</p></td>;
 })}</tr>)}</tbody></table>;
}
function ListMarker({level,label,run}:{level:Level;label:string;run:Run}){
 const {ui,fmt,diagnostic,t}=useI18n();
 const marker=level.picture?<img alt={ui("图片项目符号")} src={level.picture.data} style={{width:`${level.picture.width}pt`,height:`${level.picture.height}pt`}}/>:label;
 // 行内盒占据从编号位置到制表位的距离，正文换行继续使用列表正文缩进。
 return <span className="preview-list-marker" style={{...runCss({...run,...level.run}),textIndent:0,...(level.follow==='tab'?{display:'inline-block',minWidth:Math.max(0,level.tabPosition-level.indent+level.hanging)*cm,paddingRight:'0.2em',textAlign:level.alignment}: {})}}>{marker}{level.follow==='space'?' ':''}</span>;
}
const sceneFor=(id?:string)=>id?.startsWith('Toc')?'toc':['ReportTitle','ReportSubtitle','Signature'].includes(id??'')?'cover':id?.startsWith('Table')||['StandardTable','FigureCaption','FigureParagraph','Source','FootnoteText'].includes(id??'')?'figures':'body';
export default function Preview({project,style,list,level,onSelect,collapsed,onToggle}:{collapsed:boolean;onToggle:()=>void;project:Project;style?:Style;list?:List;level:number;onSelect:(id:string)=>void}){
 const {ui,fmt,diagnostic,t}=useI18n();
 const [tableLook,setTableLook]=useState<TableLook>(defaultTableLook);
 const [tests,setTests]=useState<Record<string,{preset:'all'|'restart'|'continue'|'custom';text:string}>>({});
 const test=list?tests[list.id]??{preset:'all' as const,text:'1, 2, 3, 2, 3, 1, 2, 3'}:undefined;
 const setTest=(change:Partial<NonNullable<typeof test>>)=>{if(list&&test)setTests(values=>({...values,[list.id]:{...test,...change}}));};
 let sequence:number[]=[],sequenceError='';
 if(list&&test){try{sequence=test.preset==='custom'?parseListTestSequence(test.text,list.levels.length):listTestSequence(list,test.preset,level);}catch(e){sequenceError=(e as Error).message;}}
 const [scene,setScene]=useState('body');const paper=useRef<HTMLDivElement>(null);const [paperHeight,setPaperHeight]=useState(0);
 const [mode,setMode]=useState<'document'|'selected'|'sequence'>('document');const [scale,setScale]=useState(.6);const container=useRef<HTMLDivElement>(null);
 const width=(project.page.size==='A4'?21:project.page.size==='A5'?14.8:21.59)*cm;const height=(project.page.size==='A4'?29.7:project.page.size==='A5'?21:27.94)*cm;const pw=project.page.orientation==='portrait'?width:height;const ph=project.page.orientation==='portrait'?height:width;
 useEffect(()=>{if(!container.current)return;const observer=new ResizeObserver(([entry])=>setScale(Math.max(.1,Math.min(1,(entry.contentRect.width-40)/pw))));observer.observe(container.current);return()=>observer.disconnect();},[pw]);
 useEffect(()=>{if(!paper.current)return;const observer=new ResizeObserver(([entry])=>setPaperHeight(entry.borderBoxSize[0]?.blockSize??entry.contentRect.height));observer.observe(paper.current);return()=>observer.disconnect();},[]);
 useEffect(()=>setScene(sceneFor(style?.id)),[style?.id]);
 const report=project.styles.some(s=>s.id==='ReportBody');
 const body=project.styles.find(s=>s.id==='ReportBody')??project.styles.find(s=>s.id==='Normal')??project.styles.find(paragraphStyle)??createStyle('paragraph',ui("正文"));
 const paragraph=(s:Style,text:string,number?:string,key?:string)=>{
 const resolved=resolveStyle(project,s);const binding=number?project.lists.flatMap(l=>l.levels).find(l=>l.linkedStyle===s.id):undefined;
 return <p key={key??s.id} tabIndex={0} role="button" title={fmt("编辑 {0}",s.name)} onClick={()=>onSelect(s.id)} onKeyDown={e=>{if(e.key==='Enter')onSelect(s.id);}} className={`sample-paragraph ${s.id===style?.id?'selected-sample':''}`} style={{...runCss(resolved.run),...paragraphCss(resolved.paragraph,resolved.run),...(binding?{paddingLeft:binding.indent*cm,textIndent:-binding.hanging*cm}:{})}}>{binding?<ListMarker level={binding} label={number!} run={resolved.run}/>:number&&<span>{number} </span>}{text}</p>;
 };
 const sample=(id:string,text:string)=>{const s=project.styles.find(s=>s.id===id);return s?paragraph(s,text,numberFor(s)):null;};

 const heading=project.styles.find(s=>s.paragraph.outlineLevel===0)??project.styles.find(s=>paragraphStyle(s)&&s.id!=='Normal');
 const second=project.styles.find(s=>s.paragraph.outlineLevel===1);
 const third=project.styles.find(s=>s.paragraph.outlineLevel===2);
 const numberFor=(s?:Style)=>{if(!s)return undefined;for(const l of project.lists){const i=l.levels.findIndex(v=>v.linkedStyle===s.id);if(i>=0)return levelLabel(l,i);}return undefined;};
 const table=project.styles.find(s=>s.type==='table');
 return <aside className="preview-panel" id="style-preview"><button className="panel-rail" aria-label={ui("展开实时预览")} title={ui("展开实时预览")} aria-expanded={false} onClick={onToggle}><PanelRight size={18}/><span>{ui("实时预览")}</span></button><div className="preview-heading"><div><Eye size={17}/><h2>{ui("实时预览")}</h2></div><div className="panel-heading-actions"><span className="preview-scale">{project.page.size} · {Math.round(scale*100)}%</span><button className="icon-button panel-collapse" aria-label={ui("收起实时预览")} title={ui("收起实时预览")} aria-expanded={!collapsed} onClick={onToggle}><PanelRight size={17}/></button></div></div><div className="preview-tabs"><button className={mode==='document'?'active':''} onClick={()=>setMode('document')}><FileText size={14}/>{ui("整体效果")}</button><button className={mode==='selected'?'active':''} onClick={()=>setMode('selected')}><Maximize2 size={14}/>{t(list?"当前列表":"当前样式",list?"Selected list":"Selected style")}</button>{list&&<button className={mode==='sequence'?'active':''} onClick={()=>setMode('sequence')}><ListTree size={14}/>{ui("编号测试")}</button>}</div>
 {report&&mode==='document'&&<nav className="report-preview-scenes" aria-label={ui("报告预览场景")}>{[['cover',ui("封面")],['toc',ui("目录")],['body',ui("正文")],['figures',ui("图表")]].map(([id,label])=><button key={id} className={scene===id?'active':''} aria-pressed={scene===id} onClick={()=>setScene(id)}>{label}</button>)}</nav>}
 {mode==='selected'&&style?.type==='table'&&<fieldset className="preview-controls table-preview-controls"><legend>{ui("预览适用区域")}</legend><div className="table-look-options">{([['firstRow',ui("标题行")],['lastRow',ui("末行")],['firstCol',ui("首列")],['lastCol',ui("末列")],['horizontal',ui("行条带")],['vertical',ui("列条带")]] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={tableLook[key]} onChange={e=>setTableLook(v=>({...v,[key]:e.target.checked}))}/>{label}</label>)}</div><p>{ui("仅控制此处预览；在 Word 中按需启用相应区域。")}</p></fieldset>}
 {mode==='sequence'&&list&&test&&<div className="preview-controls sequence-controls"><label htmlFor="sequence-preset">{ui("测试场景")}</label><select id="sequence-preset" value={test.preset} onChange={e=>setTest({preset:e.target.value as NonNullable<typeof test>['preset']})}><option value="all">{list.levels.length===1?ui("连续条目"):ui("全部九级 · 递进与返回")}</option><option value="continue">{ui("当前第")}{Math.min(level,list.levels.length-1)+1} {ui("级 · 连续编号")}</option><option value="restart">{ui("当前第")}{Math.min(level,list.levels.length-1)+1} {ui("级 · 上级变化")}</option><option value="custom">{ui("自定义层级序列")}</option></select>{test.preset==='custom'&&<><label htmlFor="sequence-input">{ui("层级序列")}</label><input id="sequence-input" value={test.text} maxLength={500} aria-invalid={!!sequenceError} aria-describedby="sequence-help" onChange={e=>setTest({text:e.target.value})} placeholder={ui("例如 1, 2, 3, 2, 3")}/><p id="sequence-help">{ui("用空格或逗号分隔，支持 1—")}{list.levels.length} {ui("级，最多 100 项。")}</p></>}{sequenceError?<p role="alert" className="form-error">{diagnostic(sequenceError)}</p>:<p>{sequence.length} {ui("个条目 · 使用当前起始值、格式与重启规则")}{test.preset==='restart'&&level>0&&list.levels[Math.min(level,list.levels.length-1)].restart===0?ui("；当前级设置为永不重启"):''}</p>}</div>}
 <div className="preview-scroll" ref={container}><div className="paper-slot" style={{width:pw*scale,height:Math.max(ph,paperHeight)*scale}}><div className="paper" ref={paper} style={{width:pw,minHeight:ph,transform:`scale(${scale})`,padding:`${project.page.top*cm}px ${project.page.right*cm}px ${project.page.bottom*cm}px ${(project.page.left+project.page.gutter)*cm}px`}}>
 {list&&(mode==='selected'||mode==='sequence')?<><p className="preview-document-label">{list.name}</p>{mode==='sequence'?simulateList(list,sequence).map((item,i)=>{const lv=list.levels[item.level];const s=project.styles.find(v=>v.id===lv.linkedStyle)??body;const r=resolveStyle(project,s);return <p key={i} className="sequence-item" data-level={item.level+1} style={{...runCss(r.run),...paragraphCss(r.paragraph,r.run),paddingLeft:lv.indent*cm,textIndent:-lv.hanging*cm}}><ListMarker level={lv} label={item.label} run={r.run}/>{list.levels.length===1?fmt("列表条目 {0}",i+1):fmt("第 {0} 级 · 条目 {1}",item.level+1,i+1)}</p>;}):list.levels.map((lv,i)=>{const s=project.styles.find(v=>v.id===lv.linkedStyle)??body;const r=resolveStyle(project,s);return <p key={i} className={i===level?'selected-sample':''} style={{...runCss(r.run),...paragraphCss(r.paragraph,r.run),paddingLeft:lv.indent*cm,textIndent:-lv.hanging*cm}}><ListMarker level={lv} label={levelLabel(list,i)} run={r.run}/>{lv.linkedStyle?s.name:fmt("第 {0} 级列表内容",i+1)}</p>;})}</>:mode==='selected'&&style?<><p className="preview-document-label">{style.name}</p>{style.type==='table'?<TablePreview style={style} project={project} look={tableLook}/>:<>{paragraph(style,ui("让每一份文档，都有清晰的秩序。"),numberFor(style))}{paragraph(style,ui("好的排版，让内容自然展开。你在这里调整的字体、段落和层级，将成为下一份文档的起点。"),'',style.id+'b')}{paragraph(style,'A clear structure makes every document easier to read. 0123456789','',style.id+'c')}</>}</>:<>
 {report?<div className={`report-scene report-scene-${scene}`}>
 {scene==='cover'&&<>{sample('ReportTitle',ui("项目研究报告"))}{sample('ReportSubtitle',ui("业务分析与阶段性结论"))}{sample('Signature',ui("研究团队 · 2026 年 9 月"))}</>}
 {scene==='toc'&&<>{sample('TocTitle',ui("目录"))}{[ui("项目概况"),ui("业务进展"),ui("产品与服务")].map((text,i)=>{const s=project.styles.find(s=>s.id==='Toc'+(i+1));if(!s)return null;const r=resolveStyle(project,s);const tab=r.paragraph.tabs.find(t=>t.alignment==='right');return <p key={s.id} role="button" tabIndex={0} title={fmt("编辑 {0}",s.name)} onClick={()=>onSelect(s.id)} onKeyDown={e=>{if(e.key==='Enter')onSelect(s.id);}} className="report-toc-entry" style={{...runCss(r.run),...paragraphCss(r.paragraph,r.run),display:'flex',alignItems:'baseline',width:tab?`min(100%, ${tab.position*cm}px)`:undefined}}><span>{text}</span><span className="report-toc-leader" style={{borderBottom:tab?.leader==='dot'?'1px dotted currentColor':tab?.leader==='hyphen'?'1px dashed currentColor':tab?.leader==='underscore'||tab?.leader==='heavy'?'1px solid currentColor':'none'}}/><span>{i+1}</span></p>;})}<p className="report-preview-note">{ui("目录条目示例，页码仅用于展示制表位效果。")}</p></>}
 {scene==='body'&&<>{sample('Heading1',ui("项目概况"))}{paragraph(body,ui("本报告梳理项目的业务情况与阶段性进展，为后续讨论提供基础。文中数据和条目均为排版示例，不代表实际项目事实。"))}{sample('Heading2',ui("业务进展"))}{sample('Heading3',ui("产品与服务"))}{paragraph(body,ui("团队围绕产品开发、客户服务和运营管理开展工作。以下展示正文编号与项目符号在报告中的排版方式。"),'',body.id+'detail')}{sample('BodyNumber1',ui("梳理主要产品及应用场景。"))}{sample('BodyNumber2',ui("明确各项工作的负责人和交付安排。"))}{sample('BodyBullet',ui("材料清单与相关说明保持一致。"))}{sample('Heading4',ui("实施安排"))}{sample('Heading5',ui("阶段任务"))}{sample('Heading6',ui("后续跟踪"))}{sample('ReportBodyPlain',ui("以上内容用于演示不同层级及无首行缩进的正文。"))}</>}
 {scene==='figures'&&<>{sample('TableCaption',ui("表 1  项目工作安排"))}{table&&<TablePreview style={table} project={project} report onSelect={onSelect}/ >}{sample('Source',ui("资料来源：示例资料，仅用于排版预览。"))}{sample('FigureCaption',ui("图 1  工作流程示意"))}{sample('FigureParagraph',ui("资料收集 → 分析整理 → 形成结论"))}{sample('FootnoteText',ui("注：图表内容为示例，可在 Word 中插入实际图表。"))}</>}
 </div>:<>
 {heading&&paragraph(heading,ui("从清晰的结构开始"),numberFor(heading))}
 {paragraph(body,ui("每一份好的文档，都从一致的样式开始。在这里定义标题、正文与编号，让格式成为表达的助力。"))}
 {second&&paragraph(second,ui("让内容各就其位"),numberFor(second))}
 {paragraph(body,ui("样式不仅是一组字体和字号，也连接着段落之间的关系。修改基础样式，继承它的内容便会一起更新。"),'',body.id+'b')}
 {third&&paragraph(third,ui("建立自己的排版习惯"),numberFor(third))}
 {paragraph(body,ui("从一个标题，到一整套层级。将常用设置保存在模板中，下次打开 Word，就可以直接开始写作。"),'',body.id+'c')}
 {project.styles.filter(s=>!['Normal',body.id,heading?.id,second?.id,third?.id].includes(s.id)&&s.type!=='table'&&(body.id!=='ReportBody'||['TableCaption','Source'].includes(s.id))).slice(0,3).map(s=>paragraph(s,s.type==='character'?ui("重点值得被看见。 Emphasis matters."):ui("统一的格式，让注意力回到内容本身。")))}
 {table&&<TablePreview style={table} project={project}/>}</>}<div className="paper-end"/>
 </>}
 </div></div><div className="preview-disclaimer">{ui("示例内容仅用于预览，空白文档导出不会包含这些文字。")}<br/>{ui("字体需在设备上安装；分页与高级效果以 Word 为准。")}</div></div>
 <div className="preview-footer"><span><span className="tiny-dot"/>{ui("修改即时预览")}</span><span>{ui("点击正文可选中样式")}</span></div></aside>;
}
