import { useI18n, LanguageSwitcher, type LocalizedMessage } from './i18n';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, Check, ChevronDown, ChevronRight, Copy, FilePlus2, FileText, FolderOpen, HelpCircle, Layers3, ListTree, List as BulletIcon, ListOrdered, Loader2, MoreHorizontal, PanelLeft, PanelRight, Plus, Redo2, Search, Settings2, Sparkles, Star, Trash2, Type, Undo2, X, AlertCircle } from 'lucide-react';
import { listKind, listKindLabels, type ListKind, bindStyle, canBaseOn, createList, createProject, createBlankProject, createStyle, makeId, paragraphStyle, removeStyle, typeLabels, validateProject, type Project, type Style } from './model';
import { useProject, STORAGE_KEY } from './useProject';
import { Field, Select, TextInput, Toggle } from './components/Fields';
import { ListEditor, PageEditor, StyleEditor } from './components/Editors';
import Preview from './components/Preview';

function download(data:Uint8Array|string,name:string,type:string){const blob=new Blob([typeof data==='string'?data:new Uint8Array(data).buffer],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function fileName(name:string){return name.trim().replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').slice(0,100)||'Word Style Project';}
function Modal({title,onClose,children,className=''}:{title:string;onClose:()=>void;children:ReactNode;className?:string}){
 const {ui,fmt,message,renderMessage,diagnostic,listLabel,t}=useI18n();
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 return <dialog ref={ref} className={`modal ${className}`} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label={ui("关闭对话框")} onClick={onClose}><X size={19}/></button></div>{children}</dialog>;
}
type Selection={kind:'style'|'list'|'page';id:string};
export default function App({active=true}:{active?:boolean}){
 const {ui,fmt,message,renderMessage,diagnostic,listLabel,t}=useI18n();
 const [expandedGroups,setExpandedGroups]=useState<Record<string,boolean>>({});
 function groupToggle(key:string,count:number,label:string){return !search.trim()&&count>3?<button className="group-toggle" aria-label={t(`${expandedGroups[key]?'收起':'展开'}${label}`,`${expandedGroups[key]?'Collapse':'Expand'} ${label}`)} aria-expanded={!!expandedGroups[key]} onClick={()=>setExpandedGroups(v=>({...v,[key]:!v[key]}))}><ChevronDown size={14} style={{transform:expandedGroups[key]?'rotate(180deg)':undefined}}/>{expandedGroups[key]?ui("收起"):fmt("展开其余 {0} 项",count-3)}</button>:null;}
 const [panels,setPanels]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('style-studio.panels.v1')??'{}');return {sidebar:saved?.sidebar!==false,preview:saved?.preview!==false};}catch{return {sidebar:true,preview:true};}});
 useEffect(()=>{try{localStorage.setItem('style-studio.panels.v1',JSON.stringify(panels));}catch{/* 面板偏好无法保存时仍允许本次切换。 */}},[panels]);
 const state=useProject(active);const {project,update}=state;const [selection,setSelection]=useState<Selection>({kind:'style',id:'Heading1'});const [level,setLevel]=useState(0);const [search,setSearch]=useState('');const [mobile,setMobile]=useState<'directory'|'editor'|'preview'>('editor');
 const [dialog,setDialog]=useState<'create'|'export'|'project'|null>(null);const [createKind,setCreateKind]=useState<Style['type']|'list'>('paragraph');const [newListKind,setNewListKind]=useState<ListKind>('multilevel');const [newName,setNewName]=useState('');const [newBase,setNewBase]=useState('Normal');const [formError,setFormError]=useState<LocalizedMessage>('');
 const [confirm,setConfirm]=useState<{title:LocalizedMessage;message:LocalizedMessage;action:()=>void;label?:LocalizedMessage}|null>(null);const [pendingImport,setPendingImport]=useState<{project:Project;warnings:string[]}|null>(null);const [loading,setLoading]=useState(false);const [notice,setNotice]=useState<{text:LocalizedMessage;error?:boolean}|null>(null);const [format,setFormat]=useState<'docx'|'dotx'>('docx');const [sample,setSample]=useState(false);const [exporting,setExporting]=useState(false);
 useEffect(()=>{const start=()=>{const mode=window.location.hash;if(mode!=='#workspace-example'&&mode!=='#workspace-blank')return;const blank=mode==='#workspace-blank';setDialog(null);setPendingImport(null);setConfirm({title:message(({ui,fmt})=>(blank?ui("从空白新建方案？"):ui("从示例新建方案？"))),message:message(({ui,fmt})=>(blank?ui("将替换当前方案，仅保留基础正文样式。可撤销恢复；建议先备份当前方案。"):ui("将载入 29 个报告样式、3 套列表及页面设置，替换当前方案。可撤销恢复；建议先备份当前方案。"))),label:message(({ui,fmt})=>(blank?ui("从空白新建"):ui("从示例新建"))),action:()=>{update(blank?createBlankProject():createProject());setSearch('');setSelection({kind:'style',id:blank?'Normal':'Heading1'});setLevel(0);}});history.replaceState(null,'','#workspace');};start();window.addEventListener('hashchange',start);return()=>window.removeEventListener('hashchange',start);},[update]);
 const fileInput=useRef<HTMLInputElement>(null);const noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const style=selection.kind==='style'?(project.styles.find(s=>s.id===selection.id)??project.styles[0]):undefined;const list=selection.kind==='list'?project.lists.find(l=>l.id===selection.id):undefined;
 function notify(text:LocalizedMessage,error=false){setNotice({text,error});if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(null),error?9000:4500);}
 function select(kind:Selection['kind'],id:string){setSelection({kind,id});if(kind==='list')setLevel(0);setMobile('editor');}
 function openCreate(kind:Style['type']|'list'='paragraph',listType:ListKind='multilevel'){setNewListKind(listType);setCreateKind(kind);setNewName('');setNewBase((kind==='paragraph'||kind==='linked')&&project.styles.some(s=>s.id==='Normal')?'Normal':'');setFormError('');setDialog('create');}
 function add(){const name=newName.trim();if(!name){setFormError(message(({ui,fmt})=>(ui("请输入名称"))));return;}if((createKind==='list'?project.lists:project.styles).some(s=>s.name.trim()===name)){setFormError(message(({ui,fmt})=>(ui("这个名称已存在，请换一个名称"))));return;}if(createKind==='list'){if(project.lists.length>=30){setFormError(message(({ui,fmt})=>(ui("每个方案最多 30 套列表"))));return;}const value=createList(name,newListKind);update({...project,lists:[...project.lists,value]});select('list',value.id);setLevel(0);}else {if(project.styles.length>=200){setFormError(message(({ui,fmt})=>(ui("每个方案最多 200 个样式"))));return;}const value=createStyle(createKind,name,newBase||undefined);if(value.next&&!project.styles.some(s=>s.id===value.next))value.next=value.id;update({...project,styles:[...project.styles,value]});select('style',value.id);}setDialog(null);notify(message(({ui,fmt})=>(ui("已创建，可继续设置格式"))));}
 function duplicate(){if(style){const copy={...structuredClone(style),id:makeId(),name:uniqueName(style.name+ui(" 副本"),project.styles)};update({...project,styles:[...project.styles,copy]});select('style',copy.id);}else if(list){const copy={...structuredClone(list),id:makeId('List'),name:uniqueName(list.name+ui(" 副本"),project.lists),listNumName:undefined,levels:list.levels.map(l=>({...structuredClone(l),linkedStyle:undefined}))};update({...project,lists:[...project.lists,copy]});select('list',copy.id);}notify(message(({ui,fmt})=>(ui("已创建副本"))));}
 function remove(){if(style){if(project.styles.length===1)return;const refs=project.styles.filter(s=>s.id!==style.id&&(s.basedOn===style.id||s.next===style.id)).length;setConfirm({title:message(({ui,fmt})=>(fmt("删除“{0}”？",style.name))),message:message(({ui,fmt})=>(refs?fmt("另有 {0} 个样式引用它。删除后会调整继承或后续样式，并解除编号绑定。可以通过撤销恢复。",refs):ui("删除后会解除关联的列表层级。可以通过撤销恢复。"))),action:()=>{update(removeStyle(project,style.id));select('style','Normal');notify(message(({ui,fmt})=>(ui("样式已删除，可撤销恢复"))));}});}else if(list){setConfirm({title:message(({ui,fmt})=>(fmt("删除“{0}”？",list.name))),message:message(({ui,fmt})=>(ui("关联的段落样式会保留，编号绑定会解除。可以通过撤销恢复。"))),action:()=>{update({...project,lists:project.lists.filter(l=>l.id!==list.id)});select('style','Normal');notify(message(({ui,fmt})=>(ui("列表已删除，可撤销恢复"))));}});}}
 function onBind(id:string,index:number,styleId?:string){const previous=project.lists.flatMap(l=>l.levels.map((lv,i)=>({list:l,index:i,level:lv}))).find(v=>v.level.linkedStyle===styleId&&!(v.list.id===id&&v.index===index));const occupied=project.lists.find(l=>l.id===id)?.levels[index].linkedStyle;const perform=()=>update(bindStyle(project,id,index,styleId));if(styleId&&(previous||(occupied&&occupied!==styleId))){setConfirm({title:message(({ui,fmt})=>(ui("调整样式与层级的关联？"))),message:message(({ui})=>ui("每个段落样式只能关联一个列表层级。此次修改将替换已有的关联，样式本身会保留。")),label:message(({ui,fmt})=>(ui("调整关联"))),action:perform});}else perform();}
 async function handleImport(file?:File){if(!file)return;setLoading(true);try{const {importFile}=await import('./import');const result=await importFile(file);setPendingImport(result);}catch(e){notify(message(({ui,fmt})=>(e instanceof Error?e.message:ui("导入失败，请检查文件格式"))),true);}finally{setLoading(false);if(fileInput.current)fileInput.current.value='';}}
 async function doExport(){setExporting(true);try{await new Promise(resolve=>setTimeout(resolve,30));const valid=validateProject(project);const {exportDocument}=await import('./export');const bytes=exportDocument(valid,{format,sample});download(bytes,`${fileName(project.name)}${sample?ui("_样式示例"):''}.${format}`,format==='dotx'?'application/vnd.openxmlformats-officedocument.wordprocessingml.template':'application/vnd.openxmlformats-officedocument.wordprocessingml.document');setDialog(null);notify(message(({ui,fmt})=>(fmt("{0}已导出，所有样式与列表定义已保留",sample?ui("样式示例"):ui("空白文件")))));}catch(e){notify(message(({ui,fmt})=>(e instanceof Error?e.message:ui("导出失败"))),true);}finally{setExporting(false);}}
 const filteredStyles=project.styles.filter(s=>s.name.toLowerCase().includes(search.toLowerCase()));const filteredLists=project.lists.filter(s=>s.name.toLowerCase().includes(search.toLowerCase()));
 return <div className={`app mobile-${mobile}${panels.sidebar?'':' sidebar-collapsed'}${panels.preview?'':' preview-collapsed'}`}><header className="app-header"><a className="brand" href="#" aria-label={ui("字序首页")}><img className="brand-mark" src="/favicon.svg?v=2" alt="" width="42" height="42"/><div><strong>{t("字序","Word Style Studio")}{t("Style Studio","")&&<span>Style Studio</span>}</strong><small>{t("Word 样式工作室","Styles & templates")}</small></div></a><div className="header-divider"/><button className="project-title" onClick={()=>setDialog('project')} title={ui("方案管理")}><span>{project.name}</span><ChevronDown size={15}/></button><div className={`save-status ${state.saveError?'error':''}`} aria-live="polite">{state.saved?<Check size={14}/>:state.saveError?<AlertCircle size={14}/>:<span className="save-dot"/>}{state.saveError?ui("保存失败"):state.loadWarning?ui("待恢复"):state.validationError?ui("待完善"):state.saved?ui("已保存到本机"):ui("保存中")}</div><div className="header-actions"><LanguageSwitcher/><div className="history-buttons"><button className="icon-button" title={ui("撤销 ⌘Z")} aria-label={ui("撤销")} disabled={!state.canUndo} onClick={state.undo}><Undo2 size={17}/></button><button className="icon-button" title={ui("重做 ⇧⌘Z")} aria-label={ui("重做")} disabled={!state.canRedo} onClick={state.redo}><Redo2 size={17}/></button></div><button className="button secondary import-button" onClick={()=>fileInput.current?.click()} disabled={loading}>{loading?<Loader2 size={16} className="spin"/>:<ArrowUpFromLine size={16}/>}{ui("导入")}</button><button className="button primary" onClick={()=>{setSample(false);setDialog('export');}}><ArrowDownToLine size={16}/>{ui("导出 Word")}</button></div></header>
 <input ref={fileInput} type="file" accept=".json,.docx,.dotx" hidden aria-label={ui("导入方案文件")} onChange={e=>void handleImport(e.target.files?.[0])}/>
 <nav className="mobile-navigation" aria-label={ui("工作区切换")}>{[['directory',ui("样式目录")],['editor',ui("设置")],['preview',ui("预览")]].map(([k,l])=><button key={k} className={mobile===k?'active':''} onClick={()=>setMobile(k as typeof mobile)}>{l}</button>)}</nav>
 <main className="workspace"><aside className="sidebar" id="style-sidebar"><button className="panel-rail" aria-label={ui("展开左侧栏")} title={ui("展开左侧栏")} aria-expanded={false} onClick={()=>setPanels(v=>({...v,sidebar:true}))}><PanelLeft size={18}/><span>{ui("样式目录")}</span></button><div className="sidebar-intro"><span className="eyebrow">{ui("工作区")}</span><div className="panel-heading-actions"><button className="icon-button" title={ui("清空样式与列表")} aria-label={ui("清空样式与列表")} onClick={()=>{setConfirm({title:message(({ui,fmt})=>(ui("清空样式与列表？"))),message:message(({ui,fmt})=>(fmt("将删除 {0} 个样式和 {1} 套列表。保留当前正文（Normal）；没有正文时创建基础正文。保留方案名称及页面设置。可通过撤销恢复。",project.styles.filter(s=>s.id!=='Normal').length,project.lists.length))),label:message(({ui,fmt})=>(ui("确认清空"))),action:()=>{update({...project,styles:project.styles.some(s=>s.id==='Normal')?project.styles.filter(s=>s.id==='Normal').map(s=>({...s,next:'Normal'})):createBlankProject().styles,lists:[]});setSearch('');select('style','Normal');notify(message(({ui,fmt})=>(ui("已清空样式与列表，可撤销恢复"))));}});}}><Trash2 size={16}/></button><button className="icon-button panel-collapse" aria-label={ui("收起左侧栏")} title={ui("收起左侧栏")} aria-expanded={true} onClick={()=>setPanels(v=>({...v,sidebar:false}))}><PanelLeft size={17}/></button><button className="icon-button" title={ui("新建样式")} aria-label={ui("新建样式")} onClick={()=>openCreate()}><Plus size={19}/></button></div></div><div className="search-input"><Search size={15}/><input aria-label={ui("查找样式或列表")} placeholder={ui("查找样式或列表")} value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌕</kbd></div>
 <div className="sidebar-scroll"><div className="nav-group-title"><span><Layers3 size={14}/>{ui("样式")}</span><span>{project.styles.length}</span></div><div className="style-list">{(search.trim()||expandedGroups.styles?filteredStyles:filteredStyles.slice(0,3)).map(s=><button key={s.id} className={`style-item ${style?.id===s.id?'selected':''}`} onClick={()=>select('style',s.id)}><span className={`style-glyph type-${s.type}`}>{s.type==='character'?'a':s.type==='table'?'▦':s.paragraph.outlineLevel!==undefined&&s.paragraph.outlineLevel<9?`H${s.paragraph.outlineLevel+1}`:'¶'}</span><span className="item-name">{s.name||ui("未命名样式")}<small>{ui(typeLabels[s.type])}</small></span>{s.quickFormat&&<Star size={12} className="quick-star"/>}</button>)}</div>{groupToggle('styles',filteredStyles.length,ui("样式"))}<button className="sidebar-add" onClick={()=>openCreate()}><Plus size={14}/>{ui("新建样式")}</button>
 {(['multilevel','bullet','numbered'] as const).map(kind=>{const Icon=kind==='multilevel'?ListTree:kind==='bullet'?BulletIcon:ListOrdered;const items=filteredLists.filter(l=>listKind(l)===kind);return <div key={kind}><div className="nav-group-title lists-title"><span><Icon size={14}/>{listLabel(kind)}</span><span>{project.lists.filter(l=>listKind(l)===kind).length}</span></div>{(search.trim()||expandedGroups[kind]?items:items.slice(0,3)).map(l=><button key={l.id} className={`list-item ${list?.id===l.id?'selected':''}`} onClick={()=>select('list',l.id)}><Icon size={17}/><span>{l.name||ui("未命名列表")}</span>{kind==='multilevel'&&<span className="count-tag">{ui("9 级")}</span>}</button>)}{groupToggle(kind,items.length,listLabel(kind))}<button className="sidebar-add" onClick={()=>openCreate('list',kind)}><Plus size={14}/>{ui("新建")}{listLabel(kind)}</button></div>;})}{search&&!filteredStyles.length&&!filteredLists.length&&<p className="empty-small">{ui("没有找到匹配的样式或列表")}</p>}
 </div><div className="sidebar-bottom"><button className={selection.kind==='page'?'active':''} onClick={()=>select('page','page')}><Settings2 size={17}/>{ui("页面设置")}<ChevronRight size={14}/></button><a className="sidebar-guide-link" href="#guide"><HelpCircle size={17}/>{ui("使用说明")}<ChevronRight size={14}/></a><div className="local-note"><span className="tiny-dot"/>{ui("文件在浏览器内处理")}</div></div></aside>
 <section className="editor-panel"><div className="editor-heading"><div><div className="breadcrumb">{selection.kind==='page'?ui("文档设置"):style?ui("样式设置"):ui("编号设置")}<ChevronRight size={12}/><span>{style?ui(typeLabels[style.type]):list?listLabel(listKind(list)):ui("页面布局")}</span></div><h1>{style?.name||list?.name||(selection.kind==='page'?ui("页面设置"):ui("选择一个样式"))}</h1></div>{(style||list)&&<div className="editor-actions"><span className="action-tooltip" data-tooltip={style?ui("复制样式"):ui("复制列表")}><button className="icon-button" aria-label={style?ui("复制样式"):ui("复制列表")} onClick={duplicate}><Copy size={16}/></button></span><span className="action-tooltip" data-tooltip={style&&project.styles.length===1?ui("最后一个样式无法删除"):style?ui("删除样式"):ui("删除列表")}><button className="icon-button" aria-label={style&&project.styles.length===1?ui("最后一个样式无法删除"):style?ui("删除样式"):ui("删除列表")} disabled={!!style&&project.styles.length===1} onClick={remove}><Trash2 size={16}/></button></span></div>}</div>
 {style?<StyleEditor project={project} style={style} onChange={s=>update({...project,styles:project.styles.map(old=>old.id===s.id?s:old)})} onProject={update} onBind={onBind}/>:list?<ListEditor project={project} list={list} level={level} onLevel={setLevel} onChange={l=>update({...project,lists:project.lists.map(old=>old.id===l.id?l:old)})} onBind={onBind} onError={m=>notify(message(({ui,fmt})=>(m)),true)}/>:selection.kind==='page'?<PageEditor project={project} onChange={update}/>:<div className="empty-small">{ui("从左侧选择或新建一个样式")}</div>}
 </section><Preview collapsed={!panels.preview} onToggle={()=>setPanels(v=>({...v,preview:!v.preview}))} project={project} style={style} list={list} level={level} onSelect={id=>select('style',id)}/></main>
 {(state.validationError||state.saveError||state.loadWarning)&&<div className="validation-banner" role="alert"><AlertCircle size={15}/><span>{diagnostic(state.loadWarning||state.saveError||state.validationError)}</span>{state.loadWarning&&<button onClick={()=>{download(localStorage.getItem(STORAGE_KEY)??'',ui("样式方案_恢复备份.json"),'application/json');state.clearRecovery();}}>{ui("下载恢复文件并继续")}</button>}</div>}
 <footer className="app-footer"><span>{project.styles.length} {ui("个样式")}<span className="footer-separator">/</span>{project.lists.length} {ui("套列表")}</span><span>DOCX · DOTX<span className="footer-separator">/</span>{ui("无需上传文档")}</span><button onClick={()=>download(JSON.stringify(project,null,2),`${fileName(project.name)}.json`,'application/json')}>{ui("备份方案")}<ArrowDownToLine size={12}/></button></footer>
 {notice&&<div role={notice.error?'alert':'status'} className={`toast ${notice.error?'error':''}`}>{notice.error?<AlertCircle size={17}/>:<Check size={17}/>}<span>{renderMessage(notice.text)}</span><button aria-label={ui("关闭提示")} onClick={()=>setNotice(null)}><X size={15}/></button></div>}
 {active&&dialog==='create'&&<Modal title={createKind==='list'?fmt("新建{0}",listLabel(newListKind)):ui("新建样式")} onClose={()=>setDialog(null)}><form onSubmit={e=>{e.preventDefault();add();}}><div className="modal-body"><Field label={ui("名称")}><TextInput label={ui("新建名称")} value={newName} onChange={v=>{setNewName(v);setFormError('');}} placeholder={createKind==='list'?ui("例如：公文编号"):ui("例如：报告正文")}/></Field>{createKind!=='list'&&<><Field label={ui("样式类型")}><Select label={ui("新建样式类型")} value={createKind} onChange={v=>{setCreateKind(v as Style['type']);setNewBase((v==='paragraph'||v==='linked')&&project.styles.some(s=>s.id==='Normal')?'Normal':'');}} options={Object.entries(typeLabels).map(([key,label])=>[key,ui(label)] as const)}/></Field><Field label={ui("基于样式")}><Select label={ui("新建样式基于")} value={newBase} onChange={setNewBase} options={[["",ui("无（文档默认值）")],...project.styles.filter(s=>createKind==='paragraph'||createKind==='linked'?paragraphStyle(s):s.type===createKind).map(s=>[s.id,s.name] as const)]}/></Field><p className="note">{ui("链接样式可以应用于整段，也可以应用于选中的文字。")}</p></>}{formError&&<p className="form-error" role="alert">{renderMessage(formError)}</p>}</div><div className="modal-footer"><button className="button secondary" type="button" onClick={()=>setDialog(null)}>{ui("取消")}</button><button className="button primary" type="submit"><Plus size={16}/>{t(createKind==='list'?'创建列表':'创建样式',createKind==='list'?'Create list':'Create style')}</button></div></form></Modal>}
 {active&&dialog==='export'&&<Modal title={ui("导出 Word 文件")} onClose={()=>!exporting&&setDialog(null)}><div className="modal-body"><p className="modal-description">{ui("你的")}{project.styles.length} {ui("个样式和")}{project.lists.length} {ui("套列表，将随文件一起保存。")}</p><div className="export-options">{([['docx',ui("Word 文档"),'.docx',ui("打开后直接开始写作")],['dotx',ui("Word 模板"),'.dotx',ui("以此创建多份新文档")]] as const).map(([id,title,ext,desc])=><button key={id} className={format===id?'selected':''} onClick={()=>setFormat(id)}><FileText size={25}/><div><strong>{title}<span>{ext}</span></strong><small>{desc}</small></div><span className="radio-mark">{format===id&&<span/>}</span></button>)}</div><Toggle label={ui("包含样式示例")} hint={ui("关闭时，导出正文为空的文件")} checked={sample} onChange={setSample}/><div className="export-summary"><Check size={15}/>{ui("保留样式、快速样式标记和列表层级定义")}</div>{state.validationError&&<p className="form-error">{ui("请先完善设置：")}{diagnostic(state.validationError)}</p>}</div><div className="modal-footer"><button className="button secondary" onClick={()=>setDialog(null)} disabled={exporting}>{ui("取消")}</button><button className="button primary" disabled={exporting||!!state.validationError} onClick={()=>void doExport()}>{exporting?<Loader2 className="spin" size={16}/>:<ArrowDownToLine size={16}/>}{t(sample?'导出示例':'导出空白文件',sample?'Export samples':'Export blank file')}</button></div></Modal>}
 {active&&dialog==='project'&&<Modal title={ui("方案管理")} onClose={()=>setDialog(null)}><div className="modal-body"><Field label={ui("方案名称")}><TextInput label={ui("方案名称")} value={project.name} onChange={name=>update({...project,name})}/></Field><div className="project-operations"><button onClick={()=>{download(JSON.stringify(project,null,2),`${fileName(project.name)}.json`,'application/json');notify(message(({ui,fmt})=>(ui("方案备份已下载"))));}}><ArrowDownToLine size={18}/><span>{ui("导出方案备份")}<small>{ui("JSON 文件，保留所有可编辑设置")}</small></span></button><button onClick={()=>{setDialog(null);fileInput.current?.click();}}><FolderOpen size={18}/><span>{ui("导入方案或 Word 文件")}<small>{ui("支持 JSON、DOCX 和 DOTX")}</small></span></button><button onClick={()=>{setDialog(null);setConfirm({title:message(({ui,fmt})=>(ui("从示例新建方案？"))),message:message(({ui,fmt})=>(ui("将载入报告示例的 29 个样式、3 套列表和页面设置，替换当前方案。可通过撤销恢复；建议先导出 JSON 备份。"))),label:message(({ui,fmt})=>(ui("从示例新建"))),action:()=>{update(createProject());setSearch('');select('style','Heading1');notify(message(({ui,fmt})=>(ui("已从示例新建方案"))));}});}}><FilePlus2 size={18}/><span>{ui("从示例新建")}<small>{ui("载入报告样式、列表和页面设置")}</small></span></button><button onClick={()=>{setDialog(null);setConfirm({title:message(({ui,fmt})=>(ui("从空白新建方案？"))),message:message(({ui,fmt})=>(ui("将替换当前方案，仅保留正文（Normal）样式，不含列表。方案名称、字体段落和页面设置恢复基础默认值。可通过撤销恢复；建议先导出 JSON 备份。"))),label:message(({ui,fmt})=>(ui("从空白新建"))),action:()=>{update(createBlankProject());setSearch('');select('style','Normal');notify(message(({ui,fmt})=>(ui("已从空白新建方案"))));}});}}><FileText size={18}/><span>{ui("从空白新建")}<small>{ui("仅保留正文样式，从基础默认设置开始")}</small></span></button></div><p className="note">{ui("方案保存在当前浏览器中，不会自动同步到其他设备。清理浏览器数据前请下载备份。")}</p></div></Modal>}

 {active&&confirm&&<Modal title={renderMessage(confirm.title)} onClose={()=>setConfirm(null)}><div className="modal-body"><p className="modal-description">{renderMessage(confirm.message)}</p></div><div className="modal-footer"><button className="button secondary" onClick={()=>setConfirm(null)}>{ui("取消")}</button><button className={`button ${confirm.label?'primary':'danger-filled'}`} onClick={()=>{confirm.action();setConfirm(null);}}>{confirm.label?renderMessage(confirm.label):ui("确认删除")}</button></div></Modal>}
 {active&&pendingImport&&<Modal title={ui("检查导入方案")} onClose={()=>setPendingImport(null)}><div className="modal-body"><div className="import-summary"><FileText size={30}/><div><strong>{pendingImport.project.name}</strong><p>{pendingImport.project.styles.length} {ui("个样式 ·")}{pendingImport.project.lists.length} {ui("套列表")}</p></div></div><p className="modal-description">{ui("应用后将替换当前方案，可通过撤销恢复。")}</p>{pendingImport.warnings.length>0?<div className="import-warnings"><h3>{t(`导入说明（${pendingImport.warnings.length}）`,`Import notes (${pendingImport.warnings.length})`)}</h3><ul>{pendingImport.warnings.map((w,i)=><li key={i}>{diagnostic(w)}</li>)}</ul></div>:<div className="export-summary"><Check size={16}/>{ui("方案已通过完整性校验")}</div>}</div><div className="modal-footer"><button className="button secondary" onClick={()=>setPendingImport(null)}>{ui("取消")}</button><button className="button primary" onClick={()=>{update(pendingImport.project);select('style','Normal');setPendingImport(null);notify(message(({ui,fmt})=>(ui("方案已导入"))));}}>{ui("应用方案")}</button></div></Modal>}
 </div>;
}
function uniqueName(base:string,items:{name:string}[]){let result=base;let i=2;while(items.some(v=>v.name===result))result=`${base} ${i++}`;return result;}
