import { ArrowRight, FileText, ListTree, Laptop, Type } from 'lucide-react';
import { STORAGE_KEY } from './useProject';
import './home.css';
export default function Home(){
 let saved=false;try{saved=!!localStorage.getItem(STORAGE_KEY);}catch{/* 存储不可用时仍可进入工作区。 */}
 const entry=saved?'继续编辑':'进入工作区';
 return <div className="home"><header className="home-header" id="home-top"><a className="home-brand" href="#home-top"><img src="/favicon.svg?v=2" width="38" height="38" alt=""/><strong>字序</strong><span>让文档有序</span></a><nav aria-label="首页导航"><a href="#guide">使用文档</a><a className="button primary" href="#workspace">{entry}<ArrowRight size={16}/></a></nav></header>
 <main><section className="home-hero"><div className="home-intro"><h1>把格式设好，<br/>让写作更专注。</h1><p>在浏览器中设置 Word 样式与列表，<br className="home-desktop-break"/>导出可复用的文档与模板。</p><a className="button primary home-cta" href="#workspace">{entry}<ArrowRight size={18}/></a><div className="home-starts"><a href="#workspace-example">从示例开始 <ArrowRight size={15}/></a><a href="#workspace-blank">从空白开始 <ArrowRight size={15}/></a></div></div><a className="home-preview" href="#workspace" aria-label="查看工作区"><img src="/images/workspace-preview.png" width="1440" height="960" alt="字序真实工作区：左侧样式目录、中间格式设置、右侧文档预览"/><span>样式、列表与预览，在一个工作区中完成 <ArrowRight size={15}/></span></a></section>
 <section className="home-steps" aria-label="三步使用流程">{[['建立样式','设置标题、正文与题注，统一字体、段落和间距。'],['关联列表','配置多级列表、项目符号或编号列表，绑定段落样式。'],['导出 Word','导出 DOCX 文档或 DOTX 模板，在 Word 中开始写作。']].map(([title,body],i)=><article key={title}><span className="home-step-number">{i+1}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</section>
 <section className="home-features"><h2>专注文档格式，从细节开始</h2><p className="home-section-lead">把常用格式保存为一套规则，让下一份文档也有章可循。</p><div className="home-feature-grid">{[{Icon:Type,title:'样式与表格',body:'管理段落、字符、链接和表格样式，设置继承关系、快速样式及表格区域格式。'},{Icon:ListTree,title:'三种列表',body:'支持多级列表、项目符号和编号列表，灵活设置层级、编号格式及重启规则。'},{Icon:FileText,title:'DOCX 与 DOTX',body:'导出带样式库的空白文档或模板，也可附带示例检查效果；用 JSON 备份完整方案。'},{Icon:Laptop,title:'本地处理',body:'无需登录，文件在浏览器内处理。方案保存在本机浏览器中，请定期下载备份。'}].map(({Icon,title,body})=><article key={title}><span className="home-feature-icon"><Icon size={27}/></span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div><aside className="home-guide-note"><span>第一次使用？了解样式与列表的关系，以及如何在 Word 中应用。</span><a href="#guide-start">阅读使用指南 <ArrowRight size={16}/></a><small>网页提供格式预览，分页及部分排版效果请以 Word 为准。本站设置样式与模板，不编辑文档正文。</small></aside></section></main>
 <footer className="home-footer"><div className="footer-closing"><div><span className="footer-eyebrow">WORD STYLE STUDIO</span><h2>让格式有序，<br/>让表达自由。</h2></div><a className="footer-enter" href="#workspace">{entry}<ArrowRight size={22}/></a></div><div className="footer-directory"><div className="footer-identity"><a href="#home-top" className="footer-logo"><img src="/favicon.svg?v=2" alt="" width="38" height="38"/><strong>字序</strong></a><p>从一套格式规则，<br/>到下一份 Word 文档。</p></div><nav aria-label="工作区入口"><h3>开始使用</h3><a href="#workspace">工作区</a><a href="#workspace-example">从示例开始</a><a href="#workspace-blank">从空白开始</a></nav><nav aria-label="帮助文档"><h3>了解字序</h3><a href="#guide">使用文档</a><a href="#guide-concepts">样式基础</a><a href="#guide-faq">常见问题</a></nav><nav aria-label="作者与项目链接"><h3>保持联系</h3><a href="https://github.com/Eric-Zhou-0302/Word-Style-Studio" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://ericzhou.net/" target="_blank" rel="noopener noreferrer">个人主页 ↗</a></nav></div><div className="footer-bottom"><span><a href="https://ericzhou.net/" target="_blank" rel="noopener noreferrer">Eric Zhou</a></span><span>字序 · Word Style Studio</span></div></footer></div>;
}
